### ISSUE TITLE
Regression: breaks Chess FEN Visualizer

### ISSUE THREAD

**Issue by adaschma** [flathub/net.ankiweb.Anki#187]
New versions of Anki on flatpak break [Chess FEN Visualizer](https://ankiweb.net/shared/info/841766736).

# Doing a flatpak-bisect reveals that the problem is introduced in: 

commit 200eee718470e87a84a2dba82c62f594f24c41051a5219cdb8a3c10f73b0311b
Parent:  05baafdf0037c1360e0fa08c18b3ecdb053ff7952751f9e873931d0fb11914c0
ContentChecksum:  5de93eb26cd3f66de8f11c9a7267dc8130e29117426a5a539b2d831b3e6eba6b
Date:  2024-11-28 15:35:23 +0000

    fix mpv x-checker, add dir-locals (f63cb680)

    Name: net.ankiweb.Anki
    Arch: x86_64
    Branch: stable
    Built with: Flatpak 1.14.10

# Running both versions from the cli shows that starting this version there are some additional qt warnings:

: flatpak run --branch=stable --arch=x86_64 --command=anki --file-forwarding net.ankiweb.Anki
Preparing to run...
2024-12-22 22:11:44,564:INFO:aqt.mediasrv: Serving on http://127.0.0.1:40253
**Qt warning: Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'**
anki_fen_vis: executing from command-line
reading: /home/adaschma/.var/app/net.ankiweb.Anki/data/Anki2/addons21/841766736/config.json
config: {'coordinates': False, 'size': 320, 'square_light': '#EDD4AE', 'square_dark': '#AB7E5B'}
Starting main loop...
**Qt warning: eglSwapBuffers failed with 0x300d, surface: 0x0
Qt warning: eglSwapBuffers failed with 0x300d, surface: 0x0**
JS warning /_anki/js/editor.js:439 No version information available for component [tex]/noerrors
JS warning /_anki/js/editor.js:439 No version information available for component [tex]/mathtools
JS warning /_anki/js/editor.js:439 No version information available for component [tex]/mhchem
2024-12-22 22:12:57,508:WARNING:waitress: unhandled close event
Exception ignored in atexit callback: <function shutdown at 0x7f7110776ac0>
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 2185, in shutdown
    h.flush()
  File "/usr/lib/python3.11/logging/__init__.py", line 1093, in flush
    if self.stream and hasattr(self.stream, "flush"):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type ErrorHandler has been deleted

# Anki about information for the last good version:

Version ⁨24.06.3 (d678e393)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Linux-6.12.6-amd64-x86_64-with-glibc2.40

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Chess FEN Visualizer ['841766736', 2023-08-20T21:36, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-12-06T02:35, 'None', mod]

===IDs of active AnkiWeb add-ons===
111623432 841766736

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
External Editor ['16727059', 2020-07-27T11:06, 'None', mod]

# Anki about information for the first bad version:
Version ⁨24.06.3 (d678e393)⁩
Python 3.11.10 Qt 6.7.3 PyQt 6.7.1

Anki 24.06.3 (d678e393) (src) (ao)
Python 3.11.10 Qt 6.7.3 PyQt 6.7.1
Platform: Linux-6.12.6-amd64-x86_64-with-glibc2.38

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Chess FEN Visualizer ['841766736', 2023-08-20T21:36, 'None', '']
HyperTTS - Add speech to your flashcards ['111623432', 2024-12-06T02:35, 'None', mod]

===IDs of active AnkiWeb add-ons===
111623432 841766736

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
External Editor ['16727059', 2020-07-27T11:06, 'None', mod]

# Symptoms

Go to Tools->Add-ons, click on "Get Add-ons" and enter the code 841766736. Restart Anki

Now create a cards with the front side being: "[fen]rnbqkbnr/ppp2ppp/8/3pp3/2PP4/8/PP2PPPP/RNBQKBNR w KQkq - 0 3[/fen]"

Now click on Cards...

On a good version notice that it show a chess board in the preview. On a broken version notice that the card shows the previously entered text ("[fen]...[/fen]")

# Python version

As the two versions use different Python versions I checked that the add-ons code is compatible with new Python versions be [running their test.py](https://github.com/adaschma/anki-fen-vis/tree/fix-test-py) which runs the replacing of the text on Python 3.12.8 without problems. So it doesn't seem to be related to that.

**Comment by rayes0** [comment]
Thank you for the report and the detailed system information. I was able to reproduce the issue. That commit was when we switched from the bundled anki version to the aqt wheel.

The Qt warnings I believe are non-fatal and are not related to the addon. If you want, you can play around with Preferences>Appearance>Video driver options.

I had a quick look through init.py of the addon and looks like this is the problem: https://github.com/lwerdna/anki-fen-vis/blob/070aad1ac61b7f16e0cc618f1f2d4118eb8330f4/distribution/__init__.py#L47-L48

The gui hook was not being set as the condition did not pass. I am considering perhaps ditching installing from wheels and compiling a package binary like the official builds, which would "fix" this issue, though I still think its a poor way to code for this check in the addon. I have made an issue in the addon repo: https://github.com/lwerdna/anki-fen-vis/issues/4

**Comment by rayes0** [comment]
As a temporary fix, you can can edit/comment out that conditional and indent the hook code to the top level in your local version of the addon, it will be in the directory ~/.var/app/net.ankiweb.Anki/data/Anki2/addons21/841766736/ for the flatpak by default if you have not messed with directories.

The addon should work normally after editing it, I have confirmed this working in the latest version.

**Comment by rayes0** [comment]
Closing for now as this is not related to the flatpak directly, please reopen or create a new issue if you are having any more problems.
