### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by cwmke** [flathub/net.ankiweb.Anki#7]
Trying this out but I get an error stating it needs mpv or mplayer installed. I'm running Fedora 28.

```
Exception in thread Thread-70:
Traceback (most recent call last):
  File "/app/share/anki/anki/sound.py", line 226, in startProcess
    env=env)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'mplayer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/app/share/anki/anki/sound.py", line 173, in run
    self.startProcess()
  File "/app/share/anki/anki/sound.py", line 229, in startProcess
    raise Exception("Did you install mplayer?")
Exception: Did you install mplayer?
```

**Comment by dsd** [comment]
Anki uses mplayer and this can't be trivially replaced with another audio player because it actually uses mplayer features (manages a playlist etc).

Wondering if there might be legal concerns with codecs etc, I looked at building a minimal mplayer only with support for MP3/vorbis/wav. But that's pretty hard.
 * When you build mplayer there is no "--disable-everything" approach as there is for ffmpeg. 
 * Even when you add the 100ish "--disable-" options that mplayer does support, the internal ffmpeg gets built with loads and loads of decoders/encoders/etc enabled
 * Hacking the configure script to force it to build the internal ffmpeg with only a minimal set of decoders causes loads of fun build difficulties
 * I see that audacity on flathub has a minimal ffmpeg build recipe so I was wondering if we could use that, but I faced build errors making mplayer use the external ffmpeg (which they do discourage)

Giving up on that, and thinking of another approach: what does Debian do?

Debian preinstalls loads of build deps and then builds mplayer with these args:
```
CONFIGURE_FLAGS = \
	--prefix=/usr \
	--confdir=/etc/mplayer \
	--enable-xvmc \
	--enable-menu \
	--enable-radio --enable-radio-capture \
	--disable-arts \
	--language=all
```

That'll use the internal ffmpeg with loads of demuxers/filters/decoders enabled.

I could just use a similarly small set of build args and let mplayer's autodetection do the rest (based on which other libs are available in the build root), also including many internal ffmpeg-supported formats. I'm thinking if Debian are OK shipping it along these lines then we should be too?

@nedrichards @ramcq  thoughts?

**Comment by cwmke** [comment]
Not sure if this helps any but doesn't Anki use mpv now with the 2.1 series?

**Comment by dsd** [comment]
Ah, I didn't realise that. mplayer is only used as a fallback if mpv is not available.
And I can copy mpv from the existing flathub io.github.GnomeMpv.json

**Comment by cwmke** [comment]
I don't have errors anymore but audio still doesn't seem to work.

**Comment by ggiaur** [comment]
I have the same problem
